SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [ods].[sp_MergeAppends_SRCtoODS]
AS
BEGIN

-- SELECT * INTO src_turnkey_appends_backup FROM src.turnkey_appends

DECLARE @Loop INT, @LoopCounter INT
DECLARE @FileName VARCHAR(100)
DECLARE @FileNameQueue TABLE (
UID INT IDENTITY(1,1) PRIMARY KEY
, FileName VARCHAR(100)
)

INSERT INTO @FileNameQueue
        ( [FileName] )
SELECT DISTINCT [FileName] FROM src.turnkey_appends ORDER BY FileName ASC

SET @Loop = (SELECT MAX(UID) FROM @FileNameQueue)
SET @LoopCounter = 1
WHILE @Loop >= @LoopCounter
BEGIN

	SET @FileName = (SELECT filename FROM @FileNameQueue WHERE UID = @LoopCounter)

	IF (SELECT COUNT(*) FROM ods.[Turnkey_Appends] WHERE [FileName] = @FileName) = 0 
	INSERT INTO ODS.Appends_FileArchive SELECT * FROM src.[TurnKey_Appends] WHERE [FileName] = @FileName
	
	MERGE INTO ods.[Turnkey_Appends] TARGET
	USING (SELECT * FROM src.[TurnKey_Appends] WHERE [FileName] = @FileName) SOURCE ON target.[AbilitecID] = [SOURCE].[AbilitecID] 
	WHEN NOT MATCHED THEN INSERT 
	(
		PersonID,
		TicketingSystemAccountID,
		AbilitecID,
		Age0002Female,
		Age0002Male,
		Age0002UnknownGender,
		Age0305Female,
		Age0305Male,
		Age0305UnknownGender,
		Age0610Female,
		Age0610Male,
		Age0610UnknownGender,
		Age1115Female,
		Age1115Male,
		Age1115UnknownGender,
		Age1617Female,
		Age1617Male,
		Age1617UnknownGender,
		AgeinTwoYearIncrements1stIndividual,
		AgeinTwoYearIncrements2ndIndividual,
		AgeinTwoYearIncrementsInputIndividual,
		ApartmentNumber,
		ApparelFemaleApparelMOBs,
		ApparelJewelryMOBs,
		ApparelMaleApparelMOBs,
		ApparelPlusSizeWomensClothingMOBs,
		ApparelTeenFashionMOBs,
		ApparelUnknownType,
		[Art&AntiqueMOBs],
		ArtsandCraftsMOBs,
		AutoSuppliesMOBs,
		BankCardHolder,
		BankFinancialServicesBanking,
		BaseRecordVerificationDate,
		BeautyMOBs,
		BookMOBs,
		BusinessOwner,
		ChildrensMerchandiseMOBs,
		CollectibleMOBs,
		CollectiblesSportsMemorabilia,
		ComputerSoftwareMOBs,
		CreditCardHolderUnknownType,
		DiscretionaryIncomeIndex,
		DwellingType,
		Education1stIndividual,
		Education2ndIndividual,
		EducationInputIndividual,
		ElectronicMOBs,
		EquestrianMOBs,
		Females1824,
		Females2534,
		Females3544,
		Females4554,
		Females5564,
		Females6574,
		Females75,
		FinanceCompanyFinancialServicesInstallCredit,
		FirstName1stIndividual,
		FirstName2ndIndividual,
		FoodMOBs,
		GasDepartmentRetailCardHolder,
		Gender1stIndividual,
		Gender2ndIndividual,
		GenderInputIndividual,
		GeneralGiftsandMerchandiseMOBs,
		GiftMOBs,
		HealthMOBs,
		HomeAssessedValueRanges,
		HomeFurnishingandDecoratingMOBs,
		HomeMarketValue,
		HomeOwnerRenter,
		HomePropertyTypeDetail,
		HomeSquareFootageActual,
		HomeYearBuiltActual,
		HouseholdAbilitecID,
		IncomeEstimatedHousehold,
		InfoBasePositiveMatchIndicator,
		InvestingActive,
		LengthofResidence,
		MailOrderBuyer,
		MailOrderDonor,
		MailOrderResponder,
		Males1824,
		Males2534,
		Males3544,
		Males4554,
		Males5564,
		Males6574,
		Males75,
		MaritalStatusintheHousehold,
		MerchandiseHighTicketMerchandiseMOBs,
		MerchandiseLowTicketMerchandiseMOBs,
		MiddleInitial1stIndividual,
		MiddleInitial2ndIndividual,
		MiscellaneousFinancialServicesInsurance,
		MiscellaneousGrocery,
		MiscellaneousMiscellaneous,
		MiscellaneousTVMailOrderPurchases,
		MotorcycleOwner,
		MusicMOBs,
		NASCAR,
		NetWorthGold,
		NetWorth,
		NumberofAdults,
		NumberofSources,
		Occupation1stIndividual,
		Occupation2ndIndividual,
		OccupationDetailInputIndividual,
		OccupationInputIndividual,
		OilCompanyOilCompany,
		OnlinePurchasingIndicator,
		OutdoorGardeningMOBs,
		[OutdoorHunting&FishingMOBs],
		OverallMatchIndicator,
		PersonicXCluster,
		PersonicxClusterCode,
		PersonicXDigitalCluster,
		PersonicxDigitalClusterCode,
		PetSuppliesMOBs,
		PrecisionLevel,
		PremiumCardHolder,
		PresenceofChildren,
		Purchase03Months,
		Purchase1012Months,
		Purchase1318Months,
		Purchase1924Months,
		Purchase24Months,
		Purchase46Months,
		Purchase79Months,
		RaceCode,
		RetailActivityDateofLast,
		RetailPurchasesMostFrequentCategory,
		RVOwner,
		SpectatorSportsAutoMotorcycleRacing,
		SpectatorSportsBaseball,
		SpectatorSportsBasketball,
		SpectatorSportsFootball,
		SpectatorSportsHockey,
		SpectatorSportsSoccer,
		SpectatorSportsTennis,
		SportsGolfMOBs,
		SportsandLeisureSC,
		SportsMOBs,
		StandardRetailCatalogShowroomRetailBuyers,
		StandardRetailHighVolumeLowEndDepartmentStoreBuyers,
		StandardRetailMainStreetRetail,
		StandardRetailMembershipWarehouse,
		StandardRetailStandardRetail,
		StandardSpecialtyComputerElectronicsBuyers,
		StandardSpecialtyFurnitureBuyers,
		StandardSpecialtyHomeImprovement,
		StandardSpecialtyHomeOfficeSupplyPurchases,
		StandardSpecialtySpecialty,
		StandardSpecialtySpecialtyApparel,
		StandardSpecialtySportingGoods,
		SuppressionMailDMA,
		TravelandEntertainmentCardHolder,
		TravelMOBs,
		TruckOwner,
		UnknownGender1824,
		UnknownGender2534,
		UnknownGender3544,
		UnknownGender4554,
		UnknownGender5564,
		UnknownGender6574,
		UnknownGender75,
		UpscaleCardHolder,
		UpscaleRetailHighEndRetailBuyersUpscaleRetail,
		UpscaleSpecialtyTravelPersonalServices,
		VehicleDominantLifestyleIndicator,
		VehicleKnownOwnedNumber,
		VehicleNewCarBuyer,
		VehicleNewUsedIndicator1stVehicle,
		VehicleNewUsedIndicator2ndVehicle,
		VideoDVDMOBs,
		WorkingWoman,
		Address1,
		Address2,
		City,
		Country,
		Email,
		FirstName,
		HomePhone,
		LastName,
		MobilePhone,
		PostalCode,
		ProspectID,
		State,
		ClientName,
		FileName,
		CopyLoadDate,
		AbilitecIDAppendDate,
		TurnkeyStandardBundleDate
	)
	VALUES
	(
		SOURCE.PersonID,
		SOURCE.TicketingSystemAccountID,
		SOURCE.AbilitecID,
		SOURCE.Age0002Female,
		SOURCE.Age0002Male,
		SOURCE.Age0002UnknownGender,
		SOURCE.Age0305Female,
		SOURCE.Age0305Male,
		SOURCE.Age0305UnknownGender,
		SOURCE.Age0610Female,
		SOURCE.Age0610Male,
		SOURCE.Age0610UnknownGender,
		SOURCE.Age1115Female,
		SOURCE.Age1115Male,
		SOURCE.Age1115UnknownGender,
		SOURCE.Age1617Female,
		SOURCE.Age1617Male,
		SOURCE.Age1617UnknownGender,
		SOURCE.AgeinTwoYearIncrements1stIndividual,
		SOURCE.AgeinTwoYearIncrements2ndIndividual,
		SOURCE.AgeinTwoYearIncrementsInputIndividual,
		SOURCE.ApartmentNumber,
		SOURCE.ApparelFemaleApparelMOBs,
		SOURCE.ApparelJewelryMOBs,
		SOURCE.ApparelMaleApparelMOBs,
		SOURCE.ApparelPlusSizeWomensClothingMOBs,
		SOURCE.ApparelTeenFashionMOBs,
		SOURCE.ApparelUnknownType,
		SOURCE.[Art&AntiqueMOBs],
		SOURCE.ArtsandCraftsMOBs,
		SOURCE.AutoSuppliesMOBs,
		SOURCE.BankCardHolder,
		SOURCE.BankFinancialServicesBanking,
		SOURCE.BaseRecordVerificationDate,
		SOURCE.BeautyMOBs,
		SOURCE.BookMOBs,
		SOURCE.BusinessOwner,
		SOURCE.ChildrensMerchandiseMOBs,
		SOURCE.CollectibleMOBs,
		SOURCE.CollectiblesSportsMemorabilia,
		SOURCE.ComputerSoftwareMOBs,
		SOURCE.CreditCardHolderUnknownType,
		SOURCE.DiscretionaryIncomeIndex,
		SOURCE.DwellingType,
		SOURCE.Education1stIndividual,
		SOURCE.Education2ndIndividual,
		SOURCE.EducationInputIndividual,
		SOURCE.ElectronicMOBs,
		SOURCE.EquestrianMOBs,
		SOURCE.Females1824,
		SOURCE.Females2534,
		SOURCE.Females3544,
		SOURCE.Females4554,
		SOURCE.Females5564,
		SOURCE.Females6574,
		SOURCE.Females75,
		SOURCE.FinanceCompanyFinancialServicesInstallCredit,
		SOURCE.FirstName1stIndividual,
		SOURCE.FirstName2ndIndividual,
		SOURCE.FoodMOBs,
		SOURCE.GasDepartmentRetailCardHolder,
		SOURCE.Gender1stIndividual,
		SOURCE.Gender2ndIndividual,
		SOURCE.GenderInputIndividual,
		SOURCE.GeneralGiftsandMerchandiseMOBs,
		SOURCE.GiftMOBs,
		SOURCE.HealthMOBs,
		SOURCE.HomeAssessedValueRanges,
		SOURCE.HomeFurnishingandDecoratingMOBs,
		SOURCE.HomeMarketValue,
		SOURCE.HomeOwnerRenter,
		SOURCE.HomePropertyTypeDetail,
		SOURCE.HomeSquareFootageActual,
		SOURCE.HomeYearBuiltActual,
		SOURCE.HouseholdAbilitecID,
		SOURCE.IncomeEstimatedHousehold,
		SOURCE.InfoBasePositiveMatchIndicator,
		SOURCE.InvestingActive,
		SOURCE.LengthofResidence,
		SOURCE.MailOrderBuyer,
		SOURCE.MailOrderDonor,
		SOURCE.MailOrderResponder,
		SOURCE.Males1824,
		SOURCE.Males2534,
		SOURCE.Males3544,
		SOURCE.Males4554,
		SOURCE.Males5564,
		SOURCE.Males6574,
		SOURCE.Males75,
		SOURCE.MaritalStatusintheHousehold,
		SOURCE.MerchandiseHighTicketMerchandiseMOBs,
		SOURCE.MerchandiseLowTicketMerchandiseMOBs,
		SOURCE.MiddleInitial1stIndividual,
		SOURCE.MiddleInitial2ndIndividual,
		SOURCE.MiscellaneousFinancialServicesInsurance,
		SOURCE.MiscellaneousGrocery,
		SOURCE.MiscellaneousMiscellaneous,
		SOURCE.MiscellaneousTVMailOrderPurchases,
		SOURCE.MotorcycleOwner,
		SOURCE.MusicMOBs,
		SOURCE.NASCAR,
		SOURCE.NetWorthGold,
		SOURCE.NetWorth,
		SOURCE.NumberofAdults,
		SOURCE.NumberofSources,
		SOURCE.Occupation1stIndividual,
		SOURCE.Occupation2ndIndividual,
		SOURCE.OccupationDetailInputIndividual,
		SOURCE.OccupationInputIndividual,
		SOURCE.OilCompanyOilCompany,
		SOURCE.OnlinePurchasingIndicator,
		SOURCE.OutdoorGardeningMOBs,
		SOURCE.[OutdoorHunting&FishingMOBs],
		SOURCE.OverallMatchIndicator,
		SOURCE.PersonicXCluster,
		SOURCE.PersonicxClusterCode,
		SOURCE.PersonicXDigitalCluster,
		SOURCE.PersonicxDigitalClusterCode,
		SOURCE.PetSuppliesMOBs,
		SOURCE.PrecisionLevel,
		SOURCE.PremiumCardHolder,
		SOURCE.PresenceofChildren,
		SOURCE.Purchase03Months,
		SOURCE.Purchase1012Months,
		SOURCE.Purchase1318Months,
		SOURCE.Purchase1924Months,
		SOURCE.Purchase24Months,
		SOURCE.Purchase46Months,
		SOURCE.Purchase79Months,
		SOURCE.RaceCode,
		SOURCE.RetailActivityDateofLast,
		SOURCE.RetailPurchasesMostFrequentCategory,
		SOURCE.RVOwner,
		SOURCE.SpectatorSportsAutoMotorcycleRacing,
		SOURCE.SpectatorSportsBaseball,
		SOURCE.SpectatorSportsBasketball,
		SOURCE.SpectatorSportsFootball,
		SOURCE.SpectatorSportsHockey,
		SOURCE.SpectatorSportsSoccer,
		SOURCE.SpectatorSportsTennis,
		SOURCE.SportsGolfMOBs,
		SOURCE.SportsandLeisureSC,
		SOURCE.SportsMOBs,
		SOURCE.StandardRetailCatalogShowroomRetailBuyers,
		SOURCE.StandardRetailHighVolumeLowEndDepartmentStoreBuyers,
		SOURCE.StandardRetailMainStreetRetail,
		SOURCE.StandardRetailMembershipWarehouse,
		SOURCE.StandardRetailStandardRetail,
		SOURCE.StandardSpecialtyComputerElectronicsBuyers,
		SOURCE.StandardSpecialtyFurnitureBuyers,
		SOURCE.StandardSpecialtyHomeImprovement,
		SOURCE.StandardSpecialtyHomeOfficeSupplyPurchases,
		SOURCE.StandardSpecialtySpecialty,
		SOURCE.StandardSpecialtySpecialtyApparel,
		SOURCE.StandardSpecialtySportingGoods,
		SOURCE.SuppressionMailDMA,
		SOURCE.TravelandEntertainmentCardHolder,
		SOURCE.TravelMOBs,
		SOURCE.TruckOwner,
		SOURCE.UnknownGender1824,
		SOURCE.UnknownGender2534,
		SOURCE.UnknownGender3544,
		SOURCE.UnknownGender4554,
		SOURCE.UnknownGender5564,
		SOURCE.UnknownGender6574,
		SOURCE.UnknownGender75,
		SOURCE.UpscaleCardHolder,
		SOURCE.UpscaleRetailHighEndRetailBuyersUpscaleRetail,
		SOURCE.UpscaleSpecialtyTravelPersonalServices,
		SOURCE.VehicleDominantLifestyleIndicator,
		SOURCE.VehicleKnownOwnedNumber,
		SOURCE.VehicleNewCarBuyer,
		SOURCE.VehicleNewUsedIndicator1stVehicle,
		SOURCE.VehicleNewUsedIndicator2ndVehicle,
		SOURCE.VideoDVDMOBs,
		SOURCE.WorkingWoman,
		SOURCE.Address1,
		SOURCE.Address2,
		SOURCE.City,
		SOURCE.Country,
		SOURCE.Email,
		SOURCE.FirstName,
		SOURCE.HomePhone,
		SOURCE.LastName,
		SOURCE.MobilePhone,
		SOURCE.PostalCode,
		SOURCE.ProspectID,
		SOURCE.State,
		SOURCE.ClientName,
		SOURCE.FileName,
		SOURCE.CopyLoadDate,
		SOURCE.AbilitecIDAppendDate,
		SOURCE.TurnkeyStandardBundleDate
	)
	WHEN MATCHED THEN UPDATE SET
		TARGET.PersonID                                                    = SOURCE.PersonID,
		TARGET.TicketingSystemAccountID 								   = SOURCE.TicketingSystemAccountID,
		TARGET.AbilitecID 												   = SOURCE.AbilitecID,
		TARGET.Age0002Female 											   = SOURCE.Age0002Female,
		TARGET.Age0002Male 												   = SOURCE.Age0002Male,
		TARGET.Age0002UnknownGender 									   = SOURCE.Age0002UnknownGender,
		TARGET.Age0305Female 											   = SOURCE.Age0305Female,
		TARGET.Age0305Male 												   = SOURCE.Age0305Male,
		TARGET.Age0305UnknownGender 									   = SOURCE.Age0305UnknownGender,
		TARGET.Age0610Female 											   = SOURCE.Age0610Female,
		TARGET.Age0610Male 												   = SOURCE.Age0610Male,
		TARGET.Age0610UnknownGender 									   = SOURCE.Age0610UnknownGender,
		TARGET.Age1115Female 											   = SOURCE.Age1115Female,
		TARGET.Age1115Male 												   = SOURCE.Age1115Male,
		TARGET.Age1115UnknownGender 									   = SOURCE.Age1115UnknownGender,
		TARGET.Age1617Female 											   = SOURCE.Age1617Female,
		TARGET.Age1617Male 												   = SOURCE.Age1617Male,
		TARGET.Age1617UnknownGender 									   = SOURCE.Age1617UnknownGender,
		TARGET.AgeinTwoYearIncrements1stIndividual 						   = SOURCE.AgeinTwoYearIncrements1stIndividual,
		TARGET.AgeinTwoYearIncrements2ndIndividual 						   = SOURCE.AgeinTwoYearIncrements2ndIndividual,
		TARGET.AgeinTwoYearIncrementsInputIndividual 					   = SOURCE.AgeinTwoYearIncrementsInputIndividual,
		TARGET.ApartmentNumber 											   = SOURCE.ApartmentNumber,
		TARGET.ApparelFemaleApparelMOBs 								   = SOURCE.ApparelFemaleApparelMOBs,
		TARGET.ApparelJewelryMOBs 										   = SOURCE.ApparelJewelryMOBs,
		TARGET.ApparelMaleApparelMOBs 									   = SOURCE.ApparelMaleApparelMOBs,
		TARGET.ApparelPlusSizeWomensClothingMOBs 						   = SOURCE.ApparelPlusSizeWomensClothingMOBs,
		TARGET.ApparelTeenFashionMOBs 									   = SOURCE.ApparelTeenFashionMOBs,
		TARGET.ApparelUnknownType 										   = SOURCE.ApparelUnknownType,
		TARGET.[Art&AntiqueMOBs] 										   = SOURCE.[Art&AntiqueMOBs],
		TARGET.ArtsandCraftsMOBs 										   = SOURCE.ArtsandCraftsMOBs,
		TARGET.AutoSuppliesMOBs 										   = SOURCE.AutoSuppliesMOBs,
		TARGET.BankCardHolder 											   = SOURCE.BankCardHolder,
		TARGET.BankFinancialServicesBanking 							   = SOURCE.BankFinancialServicesBanking,
		TARGET.BaseRecordVerificationDate 								   = SOURCE.BaseRecordVerificationDate,
		TARGET.BeautyMOBs 												   = SOURCE.BeautyMOBs,
		TARGET.BookMOBs 												   = SOURCE.BookMOBs,
		TARGET.BusinessOwner 											   = SOURCE.BusinessOwner,
		TARGET.ChildrensMerchandiseMOBs 								   = SOURCE.ChildrensMerchandiseMOBs,
		TARGET.CollectibleMOBs 											   = SOURCE.CollectibleMOBs,
		TARGET.CollectiblesSportsMemorabilia 							   = SOURCE.CollectiblesSportsMemorabilia,
		TARGET.ComputerSoftwareMOBs 									   = SOURCE.ComputerSoftwareMOBs,
		TARGET.CreditCardHolderUnknownType 								   = SOURCE.CreditCardHolderUnknownType,
		TARGET.DiscretionaryIncomeIndex 								   = SOURCE.DiscretionaryIncomeIndex,
		TARGET.DwellingType 											   = SOURCE.DwellingType,
		TARGET.Education1stIndividual 									   = SOURCE.Education1stIndividual,
		TARGET.Education2ndIndividual 									   = SOURCE.Education2ndIndividual,
		TARGET.EducationInputIndividual 								   = SOURCE.EducationInputIndividual,
		TARGET.ElectronicMOBs 											   = SOURCE.ElectronicMOBs,
		TARGET.EquestrianMOBs 											   = SOURCE.EquestrianMOBs,
		TARGET.Females1824 												   = SOURCE.Females1824,
		TARGET.Females2534 												   = SOURCE.Females2534,
		TARGET.Females3544 												   = SOURCE.Females3544,
		TARGET.Females4554 												   = SOURCE.Females4554,
		TARGET.Females5564 												   = SOURCE.Females5564,
		TARGET.Females6574 												   = SOURCE.Females6574,
		TARGET.Females75 												   = SOURCE.Females75,
		TARGET.FinanceCompanyFinancialServicesInstallCredit 			   = SOURCE.FinanceCompanyFinancialServicesInstallCredit,
		TARGET.FirstName1stIndividual 									   = SOURCE.FirstName1stIndividual,
		TARGET.FirstName2ndIndividual 									   = SOURCE.FirstName2ndIndividual,
		TARGET.FoodMOBs 												   = SOURCE.FoodMOBs,
		TARGET.GasDepartmentRetailCardHolder 							   = SOURCE.GasDepartmentRetailCardHolder,
		TARGET.Gender1stIndividual 										   = SOURCE.Gender1stIndividual,
		TARGET.Gender2ndIndividual 										   = SOURCE.Gender2ndIndividual,
		TARGET.GenderInputIndividual 									   = SOURCE.GenderInputIndividual,
		TARGET.GeneralGiftsandMerchandiseMOBs 							   = SOURCE.GeneralGiftsandMerchandiseMOBs,
		TARGET.GiftMOBs 												   = SOURCE.GiftMOBs,
		TARGET.HealthMOBs 												   = SOURCE.HealthMOBs,
		TARGET.HomeAssessedValueRanges 									   = SOURCE.HomeAssessedValueRanges,
		TARGET.HomeFurnishingandDecoratingMOBs 							   = SOURCE.HomeFurnishingandDecoratingMOBs,
		TARGET.HomeMarketValue 											   = SOURCE.HomeMarketValue,
		TARGET.HomeOwnerRenter 											   = SOURCE.HomeOwnerRenter,
		TARGET.HomePropertyTypeDetail 									   = SOURCE.HomePropertyTypeDetail,
		TARGET.HomeSquareFootageActual 									   = SOURCE.HomeSquareFootageActual,
		TARGET.HomeYearBuiltActual 										   = SOURCE.HomeYearBuiltActual,
		TARGET.HouseholdAbilitecID 										   = SOURCE.HouseholdAbilitecID,
		TARGET.IncomeEstimatedHousehold 								   = SOURCE.IncomeEstimatedHousehold,
		TARGET.InfoBasePositiveMatchIndicator 							   = SOURCE.InfoBasePositiveMatchIndicator,
		TARGET.InvestingActive 											   = SOURCE.InvestingActive,
		TARGET.LengthofResidence 										   = SOURCE.LengthofResidence,
		TARGET.MailOrderBuyer 											   = SOURCE.MailOrderBuyer,
		TARGET.MailOrderDonor 											   = SOURCE.MailOrderDonor,
		TARGET.MailOrderResponder 										   = SOURCE.MailOrderResponder,
		TARGET.Males1824 												   = SOURCE.Males1824,
		TARGET.Males2534 												   = SOURCE.Males2534,
		TARGET.Males3544 												   = SOURCE.Males3544,
		TARGET.Males4554 												   = SOURCE.Males4554,
		TARGET.Males5564 												   = SOURCE.Males5564,
		TARGET.Males6574 												   = SOURCE.Males6574,
		TARGET.Males75 													   = SOURCE.Males75,
		TARGET.MaritalStatusintheHousehold 								   = SOURCE.MaritalStatusintheHousehold,
		TARGET.MerchandiseHighTicketMerchandiseMOBs 					   = SOURCE.MerchandiseHighTicketMerchandiseMOBs,
		TARGET.MerchandiseLowTicketMerchandiseMOBs 						   = SOURCE.MerchandiseLowTicketMerchandiseMOBs,
		TARGET.MiddleInitial1stIndividual 								   = SOURCE.MiddleInitial1stIndividual,
		TARGET.MiddleInitial2ndIndividual 								   = SOURCE.MiddleInitial2ndIndividual,
		TARGET.MiscellaneousFinancialServicesInsurance 					   = SOURCE.MiscellaneousFinancialServicesInsurance,
		TARGET.MiscellaneousGrocery										   = SOURCE.MiscellaneousGrocery,
		TARGET.MiscellaneousMiscellaneous 								   = SOURCE.MiscellaneousMiscellaneous,
		TARGET.MiscellaneousTVMailOrderPurchases 						   = SOURCE.MiscellaneousTVMailOrderPurchases,
		TARGET.MotorcycleOwner 											   = SOURCE.MotorcycleOwner,
		TARGET.MusicMOBs 												   = SOURCE.MusicMOBs,
		TARGET.NASCAR 													   = SOURCE.NASCAR,
		TARGET.NetWorthGold 											   = SOURCE.NetWorthGold,
		TARGET.NetWorth 												   = SOURCE.NetWorth,
		TARGET.NumberofAdults 											   = SOURCE.NumberofAdults,
		TARGET.NumberofSources 											   = SOURCE.NumberofSources,
		TARGET.Occupation1stIndividual 									   = SOURCE.Occupation1stIndividual,
		TARGET.Occupation2ndIndividual 									   = SOURCE.Occupation2ndIndividual,
		TARGET.OccupationDetailInputIndividual 							   = SOURCE.OccupationDetailInputIndividual,
		TARGET.OccupationInputIndividual 								   = SOURCE.OccupationInputIndividual,
		TARGET.OilCompanyOilCompany 									   = SOURCE.OilCompanyOilCompany,
		TARGET.OnlinePurchasingIndicator 								   = SOURCE.OnlinePurchasingIndicator,
		TARGET.OutdoorGardeningMOBs 									   = SOURCE.OutdoorGardeningMOBs,
		TARGET.[OutdoorHunting&FishingMOBs] 							   = SOURCE.[OutdoorHunting&FishingMOBs],
		TARGET.OverallMatchIndicator 									   = SOURCE.OverallMatchIndicator,
		TARGET.PersonicXCluster 										   = SOURCE.PersonicXCluster,
		TARGET.PersonicxClusterCode 									   = SOURCE.PersonicxClusterCode,
		TARGET.PersonicXDigitalCluster 									   = SOURCE.PersonicXDigitalCluster,
		TARGET.PersonicxDigitalClusterCode 								   = SOURCE.PersonicxDigitalClusterCode,
		TARGET.PetSuppliesMOBs 											   = SOURCE.PetSuppliesMOBs,
		TARGET.PrecisionLevel 											   = SOURCE.PrecisionLevel,
		TARGET.PremiumCardHolder 										   = SOURCE.PremiumCardHolder,
		TARGET.PresenceofChildren 										   = SOURCE.PresenceofChildren,
		TARGET.Purchase03Months 										   = SOURCE.Purchase03Months,
		TARGET.Purchase1012Months 										   = SOURCE.Purchase1012Months,
		TARGET.Purchase1318Months 										   = SOURCE.Purchase1318Months,
		TARGET.Purchase1924Months 										   = SOURCE.Purchase1924Months,
		TARGET.Purchase24Months 										   = SOURCE.Purchase24Months,
		TARGET.Purchase46Months 										   = SOURCE.Purchase46Months,
		TARGET.Purchase79Months 										   = SOURCE.Purchase79Months,
		TARGET.RaceCode 												   = SOURCE.RaceCode,
		TARGET.RetailActivityDateofLast 								   = SOURCE.RetailActivityDateofLast,
		TARGET.RetailPurchasesMostFrequentCategory 						   = SOURCE.RetailPurchasesMostFrequentCategory,
		TARGET.RVOwner 													   = SOURCE.RVOwner,
		TARGET.SpectatorSportsAutoMotorcycleRacing 						   = SOURCE.SpectatorSportsAutoMotorcycleRacing,
		TARGET.SpectatorSportsBaseball 									   = SOURCE.SpectatorSportsBaseball,
		TARGET.SpectatorSportsBasketball 								   = SOURCE.SpectatorSportsBasketball,
		TARGET.SpectatorSportsFootball 									   = SOURCE.SpectatorSportsFootball,
		TARGET.SpectatorSportsHockey 									   = SOURCE.SpectatorSportsHockey,
		TARGET.SpectatorSportsSoccer 									   = SOURCE.SpectatorSportsSoccer,
		TARGET.SpectatorSportsTennis 									   = SOURCE.SpectatorSportsTennis,
		TARGET.SportsGolfMOBs 											   = SOURCE.SportsGolfMOBs,
		TARGET.SportsandLeisureSC 										   = SOURCE.SportsandLeisureSC,
		TARGET.SportsMOBs 												   = SOURCE.SportsMOBs,
		TARGET.StandardRetailCatalogShowroomRetailBuyers 				   = SOURCE.StandardRetailCatalogShowroomRetailBuyers,
		TARGET.StandardRetailHighVolumeLowEndDepartmentStoreBuyers 		   = SOURCE.StandardRetailHighVolumeLowEndDepartmentStoreBuyers,
		TARGET.StandardRetailMainStreetRetail 							   = SOURCE.StandardRetailMainStreetRetail,
		TARGET.StandardRetailMembershipWarehouse 						   = SOURCE.StandardRetailMembershipWarehouse,
		TARGET.StandardRetailStandardRetail 							   = SOURCE.StandardRetailStandardRetail,
		TARGET.StandardSpecialtyComputerElectronicsBuyers 				   = SOURCE.StandardSpecialtyComputerElectronicsBuyers,
		TARGET.StandardSpecialtyFurnitureBuyers 						   = SOURCE.StandardSpecialtyFurnitureBuyers,
		TARGET.StandardSpecialtyHomeImprovement 						   = SOURCE.StandardSpecialtyHomeImprovement,
		TARGET.StandardSpecialtyHomeOfficeSupplyPurchases 				   = SOURCE.StandardSpecialtyHomeOfficeSupplyPurchases,
		TARGET.StandardSpecialtySpecialty 								   = SOURCE.StandardSpecialtySpecialty,
		TARGET.StandardSpecialtySpecialtyApparel 						   = SOURCE.StandardSpecialtySpecialtyApparel,
		TARGET.StandardSpecialtySportingGoods 							   = SOURCE.StandardSpecialtySportingGoods,
		TARGET.SuppressionMailDMA 										   = SOURCE.SuppressionMailDMA,
		TARGET.TravelandEntertainmentCardHolder 						   = SOURCE.TravelandEntertainmentCardHolder,
		TARGET.TravelMOBs 												   = SOURCE.TravelMOBs,
		TARGET.TruckOwner 												   = SOURCE.TruckOwner,
		TARGET.UnknownGender1824 										   = SOURCE.UnknownGender1824,
		TARGET.UnknownGender2534 										   = SOURCE.UnknownGender2534,
		TARGET.UnknownGender3544 										   = SOURCE.UnknownGender3544,
		TARGET.UnknownGender4554 										   = SOURCE.UnknownGender4554,
		TARGET.UnknownGender5564 										   = SOURCE.UnknownGender5564,
		TARGET.UnknownGender6574 										   = SOURCE.UnknownGender6574,
		TARGET.UnknownGender75 											   = SOURCE.UnknownGender75,
		TARGET.UpscaleCardHolder 										   = SOURCE.UpscaleCardHolder,
		TARGET.UpscaleRetailHighEndRetailBuyersUpscaleRetail 			   = SOURCE.UpscaleRetailHighEndRetailBuyersUpscaleRetail,
		TARGET.UpscaleSpecialtyTravelPersonalServices 					   = SOURCE.UpscaleSpecialtyTravelPersonalServices,
		TARGET.VehicleDominantLifestyleIndicator 						   = SOURCE.VehicleDominantLifestyleIndicator,
		TARGET.VehicleKnownOwnedNumber 									   = SOURCE.VehicleKnownOwnedNumber,
		TARGET.VehicleNewCarBuyer 										   = SOURCE.VehicleNewCarBuyer,
		TARGET.VehicleNewUsedIndicator1stVehicle 						   = SOURCE.VehicleNewUsedIndicator1stVehicle,
		TARGET.VehicleNewUsedIndicator2ndVehicle 						   = SOURCE.VehicleNewUsedIndicator2ndVehicle,
		TARGET.VideoDVDMOBs 											   = SOURCE.VideoDVDMOBs,
		TARGET.WorkingWoman 											   = SOURCE.WorkingWoman,
		TARGET.Address1 												   = SOURCE.Address1,
		TARGET.Address2 												   = SOURCE.Address2,
		TARGET.City 													   = SOURCE.City,
		TARGET.Country 													   = SOURCE.Country,
		TARGET.Email 													   = SOURCE.Email,
		TARGET.FirstName 												   = SOURCE.FirstName,
		TARGET.HomePhone 												   = SOURCE.HomePhone,
		TARGET.LastName 												   = SOURCE.LastName,
		TARGET.MobilePhone 												   = SOURCE.MobilePhone,
		TARGET.PostalCode 												   = SOURCE.PostalCode,
		TARGET.ProspectID 												   = SOURCE.ProspectID,
		TARGET.State 													   = SOURCE.State,
		TARGET.ClientName 												   = SOURCE.ClientName,
		TARGET.FileName 												   = SOURCE.FileName,
		TARGET.CopyLoadDate 											   = SOURCE.CopyLoadDate,
		TARGET.AbilitecIDAppendDate 									   = SOURCE.AbilitecIDAppendDate,
		TARGET.TurnkeyStandardBundleDate                      			   = SOURCE.TurnkeyStandardBundleDate;
		
SET @LoopCounter = @LoopCounter + 1
END

--SELECT FileName, COUNT(*) FROM ods.[Turnkey_Appends] GROUP BY FileName Order By FileName

END
GO
